
redirect:
  enabled: false

rbac:
  enabled: false

pangeo:
  jupyterhub:

    singleuser:
      image:
        name: informaticslab/panzure-shared-env-notebook
        tag: 0.0.15

      extraEnv:
        EXAMPLES_GIT_URL: https://github.com/informatics-lab/pangeo-workshop.git
        # Workaround for https://github.com/ContinuumIO/anaconda-issues/issues/6698
        # _PYTHON_SYSCONFIGDATA_NAME: "_sysconfigdata_m_linux_x86_64-linux-gnu"


      storage:
        extraVolumes:
          - name: covid19-response
            flexVolume:
              driver: "azure/blobfuse"
              readOnly: false
              secretRef:
                name: blobfusecreds
              options:
                container: covid19-response
                tmppath: /tmp/covid19-response
                mountoptions: "--file-cache-timeout-in-seconds=600"


        extraVolumeMounts:
        - name: covid19-response
          mountPath: /data/covid19-response-blob
          readOnly: false

        - name: home
          mountPath: /data/share
          subPath: 'data-share'
        - name: home
          mountPath: /data/covid19-ancillary-data
          subPath: 'covid19-response'
          readonly: true
        - name: home
          mountPath: /envs
          subPath: 'envs/auto-build-envs'
          readOnly: true

    hub:
      
      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/informatics-lab/jade-custom-jupyterhub-templates.git"
            revision: "8de74ed597c82089bb362970db70cdd9c3bed49f"
      extraVolumeMounts:
        - mountPath: /usr/local/share/jupyterhub/custom_templates
          name: custom-templates
          subPath: "jade-custom-jupyterhub-templates/templates"
        - mountPath: /usr/local/share/jupyterhub/static/custom
          name: custom-templates
          subPath: "jade-custom-jupyterhub-templates/assets"

      extraConfig:
        customPodHook: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/',
                                        '/usr/local/share/jupyterhub/templates/']

    ingress:
      hosts:
      - covid19-response.informaticslab.co.uk
      tls:
        - hosts:
          - covid19-response.informaticslab.co.uk
          secretName: kubelego-tls-proxy-covid19-response

    auth:
      github:
        org_whitelist:
          - "pangeo-met-office"
        callbackUrl: "https://covid19-response.informaticslab.co.uk/hub/oauth_callback"
  
