
redirect:
  enabled: false

pangeo:


  jupyterhub:
    cull:
      enabled: true
      timeout: 86400 # 24 hours
    ingress:
      hosts:
      - panzure.informaticslab.co.uk
      tls:
        - hosts:
          - panzure.informaticslab.co.uk
          secretName: kubelego-tls-proxy-panzure.informaticslab.co.uk

    auth:
      github:
        callbackUrl: "https://panzure.informaticslab.co.uk/hub/oauth_callback"
