telegraf:
  enabled: false

redirect:
  enabled: false


pangeo:
  jupyterhub:

    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"

    proxy:
      secretToken: OVERRIDEME
      service:
        type: ClusterIP

    hub:

      extraConfig:
        customPodHook: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/',
                                        '/usr/local/share/jupyterhub/templates/']

      cookieSecret: OVERRIDEME

      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/met-office-lab/jade-custom-jupyterhub-templates.git"
            revision: "57685a67bd59af87dc9f2cfc792c923f2a8d178d"
      extraVolumeMounts:
        - mountPath: /usr/local/share/jupyterhub/custom_templates
          name: custom-templates
          subPath: "jade-custom-jupyterhub-templates/templates"
        - mountPath: /usr/local/share/jupyterhub/static/custom
          name: custom-templates
          subPath: "jade-custom-jupyterhub-templates/assets"

    singleuser:
      image:
        name: informaticslab/panzure-shared-env-notebook
        tag: 0.0.14

      defaultUrl: "/lab"
      cpu:
        limit: 2
        guarantee: 1
      memory:
        limit: 16G
        guarantee: 2G
      extraEnv:
        INTAKE_PATH: "/s3/informatics-pangeo-data/catalogs/weather:/s3/informatics-pangeo-data/catalogs/climate"
        EXAMPLES_GIT_URL: https://github.com/informatics-lab/pangeo-workshop.git
        # Workaround for https://github.com/ContinuumIO/anaconda-issues/issues/6698
        _PYTHON_SYSCONFIGDATA_NAME: "_sysconfigdata_m_linux_x86_64-linux-gnu"
        KRONTAB_OWNER: "$JUPYTERHUB_USER"

      fsGid: 0
      uid: 0
      cmd: ["jupyter-labhub","--allow-root"]
      storage:
        type: "static" # inspired from https://zero-to-jupyterhub.readthedocs.io/en/latest/amazon/efs_storage.html
        static:
          pvcName: "pvc-nfs"
          subPath: 'home/{username}'

        extraVolumes:

        - name: dask-config
          configMap:
            name: dask-config
        

        extraVolumeMounts:
        - name: home
          mountPath: /data-share
          subPath: 'data-share'

        - name: home
          mountPath: /envs
          subPath: 'envs/auto-build-envs'
          readOnly: true

        # - name: aws-earth-nc-files
        #   mountPath: /aws-earth-nc-files
        #   readOnly: true

        - name: dask-config
          mountPath: /etc/dask
          readOnly: true

        
    auth:
      admin:
        access: true
        users:
          - DPeterK
          - niallrobinson
          - tam203

      type: github
      github:
        clientId: OVERRIDEME
        clientSecret: OVERRIDEME
        callbackUrl: OVERRIDEME
        org_whitelist:
          - "pangeo-met-office"
        scopes:
          - "read:org"
      scopes:
        - "read:org"

    prePuller:
      hook:
        enabled: false
      continuous:
        enabled: true

    cull:
      enabled: true
      timeout: 3600
