telegraf:
  enabled: false

redirect:
  enabled: false


pangeo:
  jupyterhub:

    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"

    proxy:
      secretToken: OVERRIDEME
      service:
        type: ClusterIP

    hub:

      extraConfig:
        customPodHook: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/',
                                        '/usr/local/share/jupyterhub/templates/']

          c.KubeSpawner.profile_list = [
            {
              'display_name': 'Informatics Lab - Pangeo Notebook v0.8.1',
              'kubespawner_override': {'singleuser_image_spec': 'informaticslab/pangeo-notebook:0.8.1'},
              'default': True
            }
            ]

      cookieSecret: OVERRIDEME

      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/met-office-lab/jade-custom-jupyterhub-templates.git"
            revision: "57685a67bd59af87dc9f2cfc792c923f2a8d178d"
      extraVolumeMounts:
        - mountPath: /usr/local/share/jupyterhub/custom_templates
          name: custom-templates
          subPath: "jade-custom-jupyterhub-templates/templates"
        - mountPath: /usr/local/share/jupyterhub/static/custom
          name: custom-templates
          subPath: "jade-custom-jupyterhub-templates/assets"

    singleuser:
      image:
        name: informaticslab/pangeo-notebook
        tag: 0.8.1
      imagePullSecret:
        enabled: OVERRIDEME
        registry: OVERRIDEME
        username: OVERRIDEME
        email: OVERRIDEME
        password: OVERRIDEME
      cmd: jupyter-labhub
      defaultUrl: "/lab"
      cpu:
        limit: 2
        guarantee: 1
      memory:
        limit: 16G
        guarantee: 2G
      extraEnv:
        INTAKE_PATH: "/s3/informatics-pangeo-data/catalogs/weather:/s3/informatics-pangeo-data/catalogs/climate"
        EXAMPLES_GIT_URL: https://github.com/informatics-lab/example-notebooks.git
        DASK_KUBERNETES__DIAGNOSTICS_LINK: "{JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status"
        DASK_KUBERNETES__WORKER_TEMPLATE_PATH: "/etc/daskernetes/worker-template.yaml"
        DASK_KUBERNETES__WORKER_NAME: "dask-{JUPYTERHUB_USER}-{uuid}"
        # Workaround for https://github.com/ContinuumIO/anaconda-issues/issues/6698
        _PYTHON_SYSCONFIGDATA_NAME: "_sysconfigdata_m_linux_x86_64-linux-gnu"
        KRONTAB_OWNER: "$JUPYTERHUB_USER"

      storage:
        dynamic:
          storageClass: azurefile-env-retain
          storageAccessModes: [ReadWriteMany]

        extraVolumes:
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: daskernetes-config
          configMap:
            name: daskernetes-config
        - name: mo-uki-radar-comp-3yr
          flexVolume:
            driver: "azure/blobfuse"
            readOnly: true
            secretRef:
              name: blobfusecreds
            options:
              container: mo-uki-radar-comp-3yr
              tmppath: /tmp/mo-uki-radar-comp-3yr
              mountoptions: "--file-cache-timeout-in-seconds=600"
        - name: scratch-blob
          flexVolume:
            driver: "azure/blobfuse"
            readOnly: true
            secretRef:
              name: blobfusecreds
            options:
              container: scratch
              tmppath: /tmp/scratch-blob
              mountoptions: "--file-cache-timeout-in-seconds=600"
        - name: aws-earth-nc-files
          flexVolume:
            driver: "azure/blobfuse"
            readOnly: true
            secretRef:
              name: earthblobfusecreds
            options:
              container: aws-earth-nc-files
              tmppath: /tmp/aws-earth-nc-files
              mountoptions: "--file-cache-timeout-in-seconds=600"
        

        extraVolumeMounts:
        - name: scratch
          mountPath: /scratch
        - name: daskernetes-config
          mountPath: /etc/daskernetes
          readOnly: true
        - name: mo-uki-radar-comp-3yr
          mountPath: /mo-uki-radar-comp-3yr
          readOnly: true
        - name: scratch-blob
          mountPath: /scratch-blob
          readOnly: true
        - name: aws-earth-nc-files
          mountPath: /aws-earth-nc-files
          readOnly: true

        

    auth:
      admin:
        access: true
        users:
          - DPeterK
          - niallrobinson
          - tam203

      type: github
      github:
        clientId: OVERRIDEME
        clientSecret: OVERRIDEME
        callbackUrl: OVERRIDEME
        org_whitelist:
          - "pangeo-met-office"
        scopes:
          - "read:org"
      scopes:
        - "read:org"

    prePuller:
      hook:
        enabled: false
      continuous:
        enabled: true

    cull:
      enabled: true
      timeout: 3600
