kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pangeoKrontab
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: pangeoKrontab
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pangeoKrontab
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: pangeoKrontab
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: daskkubernetes
roleRef:
  kind: Role
  name: pangeoKrontab
apiGroup: rbac.authorization.k8s.io
