kind: ConfigMap
apiVersion: v1
metadata:
  name: krontab-config
data:
  pangeo.yaml: |-
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: krontab
    spec:
      schedule: 0 * * * *
      jobTemplate:
        metadata:
          krontabTemplate: pangeo
          annotations:
            iam.amazonaws.com/role: "arn:aws:iam::536099501702:role/pangeo"
        spec:
          template:
            metadata:
            spec:
              restartPolicy: Never
              containers:
                - name: pangeo-worker
                  image: {{ .Values.pangeo.jupyterhub.singleuser.image.name }}:{{ .Values.pangeo.jupyterhub.singleuser.image.tag }}
                  resources:
                    limits:
                      cpu: "1"
                      memory: 6G
                    requests:
                      cpu: "1"
                      memory: 6G
                  volumeMounts:
                    - name: s3
                      mountPath: /s3
                    - name: scratch
                      mountPath: /scratch
              volumes:
                - name: s3
                  flexVolume:
                    driver: "informaticslab/pysssix-flex-volume"
                    options:
                      readonly: "true"
                - name: scratch
                  flexVolume:
                    driver: "informaticslab/goofys-flex-volume"
                    options:
                      bucket: "informatics-pangeo-scratch"
                      dirMode: "0777"
                      fileMode: "0777"
