{{- if .Values.redirect.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redirect
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    {{- range .Values.redirect.from }}
    - {{ . }}
    {{- end }}
    secretName: jupyter-redirect-tls
  rules:
  {{- range .Values.redirect.from }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: redirect
          servicePort: 80
  {{- end }}
{{- end -}}