apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: scratch

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-common-retain
  resources:
    requests:
      storage: 100Gi
