apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telegraf
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: telegraf
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          resources:
            requests:
              cpu: 0.15
          image: telegraf:1.2.1-alpine
          env:
            - name: INFLUX_DB_INGEST_USER
              value: {{ .Values.telegraf.username }}
            - name: INFLUX_DB_INGEST_PASS
              value: {{ .Values.telegraf.password }}
            - name: INFLUX_DB_INGEST_URL
              value: {{ .Values.telegraf.url }}
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
              readOnly: true
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
